In [5]:
import pandas as pd
import numpy as np

matrix = np.random.uniform(1,100, [5,5])
matrix = matrix.astype(int)
matrix

array([[11, 39, 73, 62, 11],
       [33, 75, 33, 35, 45],
       [ 2, 57, 93, 84,  9],
       [93, 74, 37,  9, 11],
       [85, 30, 95, 58, 24]])

##Exercise 1 : Minimum and Maximum of Random Array

In [6]:
max_value = matrix.max()
min_value = matrix.min()
print(f'min value: {min_value}')
print(f'max value: {max_value}')


min value: 2
max value: 95


##Exercise 2 : Matrix Normalization

In [9]:
std = np.std(matrix)
mean = np.mean(matrix)
matrix = (matrix - mean) / std
matrix


array([[-1.20920704, -0.27183724,  0.86639751,  0.49814509, -1.20920704],
       [-0.4727022 ,  0.9333525 , -0.4727022 , -0.40574721, -0.07097228],
       [-1.51050447,  0.33075763,  1.53594737,  1.23464993, -1.27616203],
       [ 1.53594737,  0.89987501, -0.33879223, -1.27616203, -1.20920704],
       [ 1.26812743, -0.57313468,  1.60290235,  0.36423512, -0.77399963]])

## Exercise 3 : Evenly Spaced Elements in Array

In [14]:
array = np.linspace(0, 10, num=50, endpoint=False)
array

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

## Exercise 4 : Matrix Multiplication

In [28]:
array1 = np.random.randint(1, 10, (5,3))

array2 = np.random.randint(1, 10, (3,2))

array3 = array1 @ array2
array3


array([[ 99, 136],
       [101, 146],
       [ 79, 106],
       [116, 172],
       [ 60, 110]])

## Exercise 5

In [31]:
a = np.random.randint(1, 100, (5,12))
b = np.random.randint(1, 1150, (12,5))
c = a @ b
c

array([[444176, 379565, 428728, 422869, 446820],
       [420832, 316022, 410103, 362524, 385042],
       [342892, 246203, 283064, 365431, 284958],
       [339619, 309074, 268533, 360413, 269085],
       [451150, 420798, 490233, 507494, 546692]])