In [12]:
import numpy as np


35

##🌟 Exercise 1 : Array Creation and Manipulation

In [26]:
my_array = np.arange(1,10)
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 🌟 Exercise 2 : Type Conversion and Array Operations

In [21]:
my_list = [3.14, 2.17, 0, 1, 2]
my_array = np.array(my_list)
my_int_array = my_array.astype(int)
my_int_array

array([3, 2, 0, 1, 2])

## 🌟 Exercise 3 : Working with Multi-Dimensional Arrays

In [30]:
my_2d_array = my_array.reshape(3, 3)
my_2d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers

In [32]:
array = np.random.rand(4,5)
array

array([[0.97656001, 0.99303078, 0.76839845, 0.98510237, 0.68930536],
       [0.5934007 , 0.09456408, 0.97440635, 0.29900707, 0.57942849],
       [0.72027253, 0.31419307, 0.95973804, 0.29783933, 0.19426977],
       [0.578044  , 0.9794696 , 0.67027596, 0.48553494, 0.80475899]])

## 🌟 Exercise 5 : Indexing Arrays

In [47]:
my_array = np.arange(1,13)
my_array = my_array.reshape(3,4)
second_row = my_array[1, :]
second_row

array([5, 6, 7, 8])


## 🌟 Exercise 6 : Reversing elements

In [51]:
array = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
array[::-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 🌟 Exercise 7 : Identity Matrix

In [53]:
matrix = np.eye(4)
matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 🌟 Exercise 8 : Simple Aggregate Funcs

In [61]:
array1d = np.arange(1, 21)
sum = np.sum(array1d)
avg = np.mean(array1d)
print(f'Sum:{sum} Avg :{avg}')

Sum:210 Avg :10.5


## 🌟 Exercise 9 : Create Array and Change its Structure

In [64]:
array = np.arange(1, 21)
array = array.reshape(4,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## 🌟 Exercise 10 : Conditional Selection of Values

In [67]:
odd_array = array[array % 2 != 0]
odd_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])